name: CI-LigasEc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-13

    timeout-minutes: 10

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
       fetch-depth: 0
       
    - name: Select Xcode Version
    run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Clean Derived Data
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData
        rm -rf "${HOME}/Library/Caches/org.swift.swiftpm/"
            
    - name: Build and Test
      run: |
        set -o pipefail
        xcodebuild build test -project LigasEc.xcodeproj -scheme "LigasEcApp" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0" ONLY_ACTIVE_ARCH=YES -showBuildSettings
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results
        path: |
          TestResults
          ~/Library/Logs/scan/*.log
          
    - name: Capture Detailed Logs
      if: failure()
      run: |
        echo "Capturing detailed build logs..."
        find ~/Library/Logs/scan -type f -name "*.log"
        find ~/Library/Logs/xcodebuild -type f -name "*.log"
